# Generated by Django 4.2.27 on 2026-01-10 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('scraping', '0001_initial'),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('alert_type', models.CharField(choices=[('price_increase', 'Рост цены'), ('price_decrease', 'Падение цены'), ('new_negative_review', 'Новый негативный отзыв'), ('new_positive_competitor', 'Позитивный отзыв конкурента'), ('out_of_stock', 'Нет в наличии')], max_length=30, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('threshold_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Для алертов на цену', max_digits=5, null=True, verbose_name='Порог (%)')),
                ('threshold_rating', models.PositiveSmallIntegerField(blank=True, help_text='Для алертов на отзывы', null=True, verbose_name='Порог рейтинга')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=20, verbose_name='Канал')),
                ('recipients', models.JSONField(default=list, help_text='["chat_id", "@username"]', verbose_name='Получатели')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Не чаще чем раз в N часов', verbose_name='Пауза (часы)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='products.product', verbose_name='Товар')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='retailers.retailer', verbose_name='Ретейлер')),
            ],
            options={
                'verbose_name': 'Правило оповещения',
                'verbose_name_plural': 'Правила оповещений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время срабатывания')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('details', models.JSONField(default=dict, help_text='{"old_price": 100, "new_price": 120, "pct_change": 20}', verbose_name='Детали')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('delivery_error', models.TextField(blank=True, verbose_name='Ошибка доставки')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule', verbose_name='Правило')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='products.listing', verbose_name='Листинг')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='scraping.snapshotprice', verbose_name='Снимок')),
            ],
            options={
                'verbose_name': 'Событие оповещения',
                'verbose_name_plural': 'События оповещений',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
