# Generated by Django 4.2.27 on 2026-01-10 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('report_type', models.CharField(choices=[('price_matrix', 'Матрица цен'), ('review_matrix', 'Матрица отзывов'), ('insights_matrix', 'Матрица выводов'), ('full', 'Полный отчёт'), ('product_journal', 'Журнал по товару')], max_length=30, verbose_name='Тип отчёта')),
                ('period_from', models.DateField(verbose_name='Период с')),
                ('period_to', models.DateField(verbose_name='Период по')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='{"is_own": true, "retailer_id": "..."}', verbose_name='Фильтры')),
                ('file_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к файлу')),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Скачиваний')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-generated_at'],
            },
        ),
    ]
