# Generated by Django 4.2.27 on 2026-01-10 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('base_url', models.URLField(verbose_name='Базовый URL')),
                ('connector_class', models.CharField(choices=[('apps.scraping.connectors.ozon.OzonConnector', 'Ozon'), ('apps.scraping.connectors.vkusvill.VkusvillConnector', 'ВкусВилл'), ('apps.scraping.connectors.perekrestok.PerekrestokConnector', 'Перекрёсток'), ('apps.scraping.connectors.lavka.LavkaConnector', 'Яндекс Лавка')], max_length=100, verbose_name='Класс коннектора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('requires_auth', models.BooleanField(default=False, verbose_name='Требует авторизации')),
                ('default_region', models.CharField(default='moscow', max_length=50, verbose_name='Регион по умолчанию')),
                ('rate_limit_rpm', models.PositiveIntegerField(default=10, verbose_name='Лимит запросов/мин')),
                ('product_url_pattern', models.CharField(blank=True, help_text='Regex для извлечения ID товара из URL', max_length=255, verbose_name='Паттерн URL товара')),
            ],
            options={
                'verbose_name': 'Ретейлер',
                'verbose_name_plural': 'Ретейлеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetailerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('region_code', models.CharField(default='moscow', max_length=50, verbose_name='Код региона')),
                ('cookies_encrypted', models.BinaryField(blank=True, null=True, verbose_name='Cookies (зашифровано)')),
                ('local_storage_encrypted', models.BinaryField(blank=True, null=True, verbose_name='LocalStorage (зашифровано)')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Валидна')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='retailers.retailer', verbose_name='Ретейлер')),
            ],
            options={
                'verbose_name': 'Сессия ретейлера',
                'verbose_name_plural': 'Сессии ретейлеров',
                'unique_together': {('retailer', 'region_code')},
            },
        ),
    ]
