# Generated by Django 4.2.27 on 2026-01-10 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('is_own', models.BooleanField(default=True, help_text='Отметьте для собственных товаров, снимите для конкурентов', verbose_name='Наш товар')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='Тип продукта')),
                ('packaging_type', models.CharField(blank=True, choices=[('doypack', 'Дой-пак'), ('box', 'Коробка'), ('bag', 'Пакет'), ('tray', 'Лоток'), ('jar', 'Банка'), ('other', 'Другое')], max_length=20, verbose_name='Тип упаковки')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('caliber', models.CharField(blank=True, max_length=50, verbose_name='Калибр')),
                ('has_pit', models.BooleanField(blank=True, null=True, verbose_name='С косточкой')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='Сорт')),
                ('extra_attrs', models.JSONField(blank=True, default=dict, help_text='JSON с дополнительными характеристиками', verbose_name='Дополнительные атрибуты')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('external_url', models.URLField(max_length=500, verbose_name='URL товара')),
                ('external_id', models.CharField(blank=True, help_text='SKU или ID товара на площадке', max_length=100, verbose_name='ID на площадке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('scrape_priority', models.PositiveSmallIntegerField(default=5, help_text='1-10, выше = раньше в очереди', verbose_name='Приоритет')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний сбор')),
                ('last_scrape_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product', verbose_name='Товар')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='retailers.retailer', verbose_name='Ретейлер')),
            ],
            options={
                'verbose_name': 'Листинг',
                'verbose_name_plural': 'Листинги',
                'ordering': ['-scrape_priority', 'product__name'],
                'unique_together': {('product', 'retailer')},
            },
        ),
    ]
