# Generated by Django 4.2.27 on 2026-01-10 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('period_month', models.DateField(verbose_name='Период (месяц)')),
                ('analysis_type', models.CharField(choices=[('monthly', 'Ежемесячный'), ('quarterly', 'Квартальный')], default='monthly', max_length=20, verbose_name='Тип анализа')),
                ('remove_suggestions', models.TextField(blank=True, verbose_name='Что убрать')),
                ('add_packaging_suggestions', models.TextField(blank=True, verbose_name='Добавить в упаковку')),
                ('add_taste_suggestions', models.TextField(blank=True, verbose_name='Изменить во вкусе')),
                ('key_positive_themes', models.JSONField(default=list, verbose_name='Позитивные темы')),
                ('key_negative_themes', models.JSONField(default=list, verbose_name='Негативные темы')),
                ('competitor_insights', models.TextField(blank=True, verbose_name='Инсайты конкурентов')),
                ('raw_llm_response', models.JSONField(default=dict, verbose_name='Ответ LLM')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Токенов')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерировано')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='products.listing', verbose_name='Листинг')),
            ],
            options={
                'verbose_name': 'Анализ отзывов',
                'verbose_name_plural': 'Анализы отзывов',
                'ordering': ['-period_month'],
                'unique_together': {('listing', 'period_month', 'analysis_type')},
            },
        ),
    ]
