# Generated by Django 4.2.27 on 2026-01-10 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('trigger_type', models.CharField(choices=[('manual', 'Вручную'), ('scheduled', 'По расписанию')], default='manual', max_length=20, verbose_name='Тип запуска')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('listings_total', models.PositiveIntegerField(default=0, verbose_name='Всего листингов')),
                ('listings_success', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('listings_failed', models.PositiveIntegerField(default=0, verbose_name='С ошибками')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('retailer', models.ForeignKey(blank=True, help_text='NULL = все ретейлеры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_sessions', to='retailers.retailer', verbose_name='Ретейлер')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
            ],
            options={
                'verbose_name': 'Сессия сбора',
                'verbose_name_plural': 'Сессии сбора',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сбора')),
                ('period_month', models.DateField(verbose_name='Период (месяц)')),
                ('reviews_1_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов 1*')),
                ('reviews_2_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов 2*')),
                ('reviews_3_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов 3*')),
                ('reviews_4_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов 4*')),
                ('reviews_5_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов 5*')),
                ('reviews_1_3_count', models.PositiveIntegerField(default=0, help_text='Сумма 1+2+3', verbose_name='Негативных (1-3*)')),
                ('new_reviews_count', models.PositiveIntegerField(default=0, verbose_name='Новых отзывов')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_snapshots', to='products.listing', verbose_name='Листинг')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_snapshots', to='scraping.scrapesession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Снимок отзывов',
                'verbose_name_plural': 'Снимки отзывов',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['listing', 'period_month'], name='scraping_sn_listing_fccfa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сбора')),
                ('period_month', models.DateField(help_text='Первый день месяца для группировки', verbose_name='Период (месяц)')),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обычная цена')),
                ('price_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Акционная цена')),
                ('price_card', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по карте')),
                ('price_final', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная из всех цен', max_digits=10, null=True, verbose_name='Итоговая цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Средний рейтинг')),
                ('reviews_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во отзывов')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='products.listing', verbose_name='Листинг')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_snapshots', to='scraping.scrapesession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Снимок цены',
                'verbose_name_plural': 'Снимки цен',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['listing', 'period_month'], name='scraping_sn_listing_178edc_idx'), models.Index(fields=['period_month'], name='scraping_sn_period__118da9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('external_id', models.CharField(help_text='ID на площадке для дедупликации', max_length=100, verbose_name='ID отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('pros', models.TextField(blank=True, verbose_name='Достоинства')),
                ('cons', models.TextField(blank=True, verbose_name='Недостатки')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сбора')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Позитивный'), ('neutral', 'Нейтральный'), ('negative', 'Негативный')], max_length=20, verbose_name='Тональность')),
                ('topics', models.JSONField(blank=True, default=list, help_text='["упаковка", "вкус", ...]', verbose_name='Темы')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.listing', verbose_name='Листинг')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-published_at', '-scraped_at'],
                'indexes': [models.Index(fields=['listing', 'rating'], name='scraping_re_listing_f3ce41_idx'), models.Index(fields=['is_processed'], name='scraping_re_is_proc_02b341_idx')],
                'unique_together': {('listing', 'external_id')},
            },
        ),
    ]
