# Generated by Django 4.2.27 on 2026-01-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('url', models.URLField(max_length=2000, verbose_name='URL товара')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('product_title', models.CharField(blank=True, max_length=500, verbose_name='Название товара')),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обычная цена')),
                ('price_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Акционная цена')),
                ('price_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во отзывов')),
                ('in_stock', models.BooleanField(blank=True, null=True, verbose_name='В наличии')),
                ('reviews_data', models.JSONField(blank=True, default=list, help_text='Список отзывов в формате JSON', verbose_name='Данные отзывов')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время обработки')),
                ('retailer', models.ForeignKey(blank=True, help_text='Определяется автоматически из URL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_imports', to='retailers.retailer', verbose_name='Ретейлер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_imports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ручной импорт',
                'verbose_name_plural': 'Ручные импорты',
                'ordering': ['-created_at'],
            },
        ),
    ]
