# Generated by Django 4.2.27 on 2026-01-10 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0002_add_manual_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('group_type', models.CharField(choices=[('own', 'Наши товары'), ('competitor', 'Конкуренты')], default='competitor', max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#6b7280', help_text='HEX цвет для отображения', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Группа мониторинга',
                'verbose_name_plural': 'Группы мониторинга',
                'ordering': ['group_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='manualimport',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Ваше название для товара (для отчётов)', max_length=200, verbose_name='Своё название'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Автоматически собирать данные каждый месяц', verbose_name='Повторять ежемесячно'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='monitoring_period',
            field=models.DateField(blank=True, help_text='Месяц мониторинга (первый день месяца)', null=True, verbose_name='Период мониторинга'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Разница с предыдущим периодом', max_digits=10, null=True, verbose_name='Изменение цены'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='price_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Изменение цены %'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='price_previous',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предыдущая цена'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='product_type',
            field=models.CharField(choices=[('own', 'Наш товар'), ('competitor', 'Конкурент')], default='competitor', max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='review_insights',
            field=models.JSONField(blank=True, default=dict, help_text='Анализ отзывов: темы, настроения, ключевые слова', verbose_name='Инсайты из отзывов'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='reviews_negative_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отрицательных отзывов'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='reviews_neutral_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Нейтральных отзывов'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='reviews_positive_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Положительных отзывов'),
        ),
        migrations.AddIndex(
            model_name='manualimport',
            index=models.Index(fields=['user', 'product_type'], name='scraping_ma_user_id_b61cae_idx'),
        ),
        migrations.AddIndex(
            model_name='manualimport',
            index=models.Index(fields=['user', 'monitoring_period'], name='scraping_ma_user_id_4cffff_idx'),
        ),
        migrations.AddIndex(
            model_name='manualimport',
            index=models.Index(fields=['url'], name='scraping_ma_url_6625d5_idx'),
        ),
        migrations.AddField(
            model_name='monitoringgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='manualimport',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='scraping.monitoringgroup', verbose_name='Группа'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringgroup',
            unique_together={('user', 'name')},
        ),
    ]
